# Generated by Django 2.2 on 2020-10-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babbles', '0003_auto_20201020_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, to='babbles.Tweet'),
            preserve_default='True',
        ),
    ]
